### ISSUE TITLE
Your code is showing me this error. Can you please help me to fix it?

### ISSUE THREAD

**Issue by muhammadatifaltaf** [hadasu/CNN_web_crawler#2]
2023-04-09 23:27:28,617 INFO:Page is not of type "article". Actual type is: None

**Comment by hadasu** [comment]
Hi Muhammad, 
This message is not an error it is information.
When the crawler came across a URL that is not an article you will get the following information message - "INFO:Page is not of type "article". Actual type is: None " The crawler will still collect the URLs in this website and continue to look for articles. 
I checked the code and did find an error about something else that prevent the use of the program. 
I fixed it, please try again now.
